# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Prepare client
      run: npm install --prefix web-client
    - name: Build client
      run: npm run build --prefix web-client
    - name: Run client e2e
      run: npm run e2e --prefix web-client
    - name: Prepare server
      run: npm install
    - name: Run server tests
      run: npm run test
    - name: Run integration tests
      run: npm run test:integration
      env:
        CI: true
